---
variables:
  PROJECT: global-data-resources
  PRODUCTION_PROJECT: global-data-resources
  TESTING_PROJECT: global-data-resources
  REGION: europe-west1

stages:
  - deploy
  - release

.make_dependencies: &make_dependencies
  tags:
    - Global Data
  image:
    name: greenpeaceinternational/gitlab-data-civis-deployer:latest
  before_script:
    - gcloud auth activate-service-account --key-file $SERVICE_ACCOUNT
    - export GOOGLE_APPLICATION_CREDENTIALS=$SERVICE_ACCOUNT
    - gcloud config set project $PROJECT
    - gcloud config set functions/region $REGION
    - make install

deploy:
  <<: *make_dependencies
  stage: deploy
  variables:
    PROJECT: $TESTING_PROJECT
  environment:
    name: testing
  only:
    - develop
  script: make
  retry: 2
  artifacts:
    name: "$CI_JOB_NAME:source"
    expire_in: 1 months
    paths:
      - tf/test/build/bq-gcs.zip

release:
  stage: release
  <<: *make_dependencies
  retry: 2
  only:
    # Matches any semver tag:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
    - develop
  script:
    - make release
